####
## Metadata Registry Tests for Agentic Data Quality Triage
## Author: Mario Caesar // hello@caesarmar.io // https://caesarmar.io/
####

"""Validate metadata contracts, sync planning, tombstones, and exact verification."""

# --- Importing Libraries
from __future__ import annotations

from dataclasses import replace
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

import pytest
from pydantic import ValidationError

from pipelines.metadata.config import (
    METADATA_REGISTRY_NAMES as PIPELINE_METADATA_REGISTRY_NAMES,
    MetadataRegistryConfig,
    load_named_metadata_registry,
)
from dags.dq_platform.metadata_registry import METADATA_REGISTRY_NAMES as AIRFLOW_METADATA_REGISTRY_NAMES
from pipelines.metadata.registry import (
    METADATA_ASSET_COLUMNS,
    MetadataRegistryEntry,
    build_metadata_sync_plan,
    clickhouse_text,
    metadata_asset_hash,
    project_relative_config_path,
    verify_metadata_registry,
)


# --- Defining Test Fakes
class FakeQueryResult:
    """
    Minimal clickhouse-connect query result for metadata verification tests.

    Attributes:
        column_names: Registry columns returned by ClickHouse.
        result_rows: Latest metadata registry rows.
    """

    def __init__(self, column_names: tuple[str, ...], result_rows: list[tuple[Any, ...]]) -> None:
        """
        Initialize the fake result from metadata entries.

        Args:
            column_names: Columns exposed by the fake query result.
            result_rows: Rows exposed by the fake query result.

        Returns:
            None.
        """
        self.column_names = column_names
        self.result_rows  = result_rows


class FakeClickHouseClient:
    """
    Read-only ClickHouse fake returning preconfigured latest registry rows.

    Attributes:
        entries: Latest rows exposed through query().
    """

    def __init__(
        self,
        entries: list[MetadataRegistryEntry],
        missing_physical_assets: set[str] | None = None,
    ) -> None:
        """
        Initialize the fake metadata registry state.

        Args:
            entries: Latest entries returned for registry queries.
            missing_physical_assets: Optional qualified names omitted from system.tables.

        Returns:
            None.
        """
        self.entries                 = entries
        self.missing_physical_assets = missing_physical_assets or set()

    def query(self, query: str) -> FakeQueryResult:
        """
        Validate bounded latest-state SQL and return configured entries.

        Args:
            query: Registry SELECT generated by the runtime adapter.

        Returns:
            FakeQueryResult containing configured entries.
        """
        if "FROM system.tables" in query:
            physical_rows = [
                (entry.database_name, entry.table_name)
                for entry in self.entries
                if entry.qualified_name not in self.missing_physical_assets
            ]

            return FakeQueryResult(("database", "name"), physical_rows)

        assert "FROM dq.metadata_assets FINAL" in query
        assert "LIMIT 1000" in query

        return FakeQueryResult(
            METADATA_ASSET_COLUMNS,
            [entry.as_insert_row() for entry in self.entries],
        )


# --- Defining Test Helpers
def load_orders_contract() -> tuple[MetadataRegistryConfig, Path]:
    """
    Load the repository orders metadata contract.

    Returns:
        Validated config and absolute source path.
    """
    return load_named_metadata_registry("orders")


def initial_plan() -> tuple[MetadataRegistryConfig, Path, tuple[MetadataRegistryEntry, ...]]:
    """
    Build deterministic initial active entries for all orders assets.

    Returns:
        Config, source path, and newly activated entries.
    """
    config, path = load_orders_contract()
    plan = build_metadata_sync_plan(
        config=config,
        source_path=path,
        current_entries=[],
        base_version=100,
        synced_at=datetime(2026, 8, 7, tzinfo=timezone.utc),
    )

    return config, path, plan.entries_to_insert


# --- Defining Config Tests
def test_airflow_and_pipeline_registry_allowlists_remain_aligned() -> None:
    """
    Ensure DAG-safe constants cannot drift from runtime registry configuration.

    Returns:
        None.
    """
    assert AIRFLOW_METADATA_REGISTRY_NAMES == PIPELINE_METADATA_REGISTRY_NAMES


def test_orders_metadata_contract_is_explicit_and_normalized() -> None:
    """
    Ensure current warehouse assets have ownership, grain, SLA, and trust metadata.

    Returns:
        None.
    """
    config, _ = load_orders_contract()
    assets    = {asset.qualified_name: asset for asset in config.assets}

    assert set(assets) == {"dq.raw_orders", "dq.stg_orders", "dq.fct_orders_daily"}
    assert assets["dq.fct_orders_daily"].certification_status == "certified"
    assert assets["dq.fct_orders_daily"].criticality == "critical"
    assert assets["dq.raw_orders"].sla_timezone == "Asia/Bangkok"
    assert assets["dq.raw_orders"].tags == sorted(assets["dq.raw_orders"].tags)
    assert all(asset.grain and asset.technical_owner and asset.business_owner for asset in config.assets)


def test_metadata_contract_rejects_inconsistent_qualified_name() -> None:
    """
    Ensure a contract cannot point its qualified name at a different table.

    Returns:
        None.
    """
    config, _ = load_orders_contract()
    raw        = config.model_dump(mode="json")
    raw["assets"][0]["qualified_name"] = "dq.wrong_table"

    with pytest.raises(ValidationError, match="qualified_name must equal"):
        MetadataRegistryConfig.model_validate(raw)


def test_metadata_contract_rejects_duplicate_assets() -> None:
    """
    Ensure one source registry cannot define the same qualified asset twice.

    Returns:
        None.
    """
    config, _ = load_orders_contract()
    raw        = config.model_dump(mode="json")
    raw["assets"].append(dict(raw["assets"][0]))

    with pytest.raises(ValidationError, match="Duplicate metadata assets"):
        MetadataRegistryConfig.model_validate(raw)


def test_metadata_hash_is_stable_after_tag_normalization() -> None:
    """
    Ensure semantically equivalent tag order does not create registry churn.

    Returns:
        None.
    """
    config, _ = load_orders_contract()
    raw        = config.assets[0].model_dump(mode="json")
    raw["tags"] = list(reversed(raw["tags"])) + [raw["tags"][0]]
    normalized = type(config.assets[0]).model_validate(raw)

    assert metadata_asset_hash(config.assets[0], config.dataset) == metadata_asset_hash(normalized, config.dataset)


def test_clickhouse_fixed_string_hash_is_decoded_without_byte_repr() -> None:
    """
    Ensure FixedString hashes compare as text rather than Python byte representations.

    Returns:
        None.
    """
    digest = "a" * 64

    assert clickhouse_text(digest.encode("utf-8")) == digest
    assert clickhouse_text(digest.encode("utf-8") + b"\x00\x00") == digest


def test_metadata_source_path_must_remain_inside_project() -> None:
    """
    Ensure registry ownership cannot reference an arbitrary external path.

    Returns:
        None.
    """
    with pytest.raises(ValueError, match="inside the project root"):
        project_relative_config_path(Path.home() / "outside-metadata.yml")


# --- Defining Sync Plan Tests
def test_initial_sync_activates_every_asset() -> None:
    """
    Ensure an empty registry receives one active version per configured asset.

    Returns:
        None.
    """
    config, _, entries = initial_plan()

    assert len(entries) == len(config.assets) == 3
    assert all(entry.is_active for entry in entries)
    assert [entry.version for entry in entries] == [100, 101, 102]


def test_repeated_sync_is_idempotent() -> None:
    """
    Ensure unchanged active hashes produce no ClickHouse inserts.

    Returns:
        None.
    """
    config, path, current = initial_plan()
    plan = build_metadata_sync_plan(
        config=config,
        source_path=path,
        current_entries=current,
        base_version=200,
        synced_at=datetime(2026, 8, 8, tzinfo=timezone.utc),
    )

    assert plan.entries_to_insert == ()
    assert set(plan.unchanged_names) == {asset.qualified_name for asset in config.assets}


def test_changed_asset_appends_one_new_active_version() -> None:
    """
    Ensure a contract change updates only the affected asset.

    Returns:
        None.
    """
    config, path, current = initial_plan()
    changed_assets        = list(config.assets)
    changed_assets[0]     = changed_assets[0].model_copy(
        update={"description": changed_assets[0].description + " This text records a controlled contract update."}
    )
    changed_config = config.model_copy(update={"assets": changed_assets})

    plan = build_metadata_sync_plan(
        config=changed_config,
        source_path=path,
        current_entries=current,
        base_version=200,
        synced_at=datetime(2026, 8, 8, tzinfo=timezone.utc),
    )

    assert plan.activated_names == ("dq.raw_orders",)
    assert len(plan.entries_to_insert) == 1
    assert plan.entries_to_insert[0].version == 200


def test_removed_asset_creates_tombstone_without_deletion() -> None:
    """
    Ensure removing an asset appends an inactive latest version.

    Returns:
        None.
    """
    config, path, current = initial_plan()
    current_by_name       = {entry.qualified_name: entry for entry in current}
    reduced_config        = config.model_copy(update={"assets": config.assets[:-1]})
    plan = build_metadata_sync_plan(
        config=reduced_config,
        source_path=path,
        current_entries=current,
        base_version=200,
        synced_at=datetime(2026, 8, 8, tzinfo=timezone.utc),
    )

    assert plan.tombstoned_names == ("dq.fct_orders_daily",)
    assert len(plan.entries_to_insert) == 1
    assert plan.entries_to_insert[0].is_active is False
    assert plan.entries_to_insert[0].config_sha256 == current_by_name["dq.fct_orders_daily"].config_sha256


def test_readding_tombstoned_asset_reactivates_it() -> None:
    """
    Ensure a later contract can safely reactivate a previously removed asset.

    Returns:
        None.
    """
    config, path, current = initial_plan()
    current_by_name       = {entry.qualified_name: entry for entry in current}
    tombstoned = replace(
        current_by_name["dq.fct_orders_daily"],
        is_active=False,
        version=200,
        synced_at=datetime(2026, 8, 8, tzinfo=timezone.utc),
    )
    latest = [
        tombstoned if entry.qualified_name == "dq.fct_orders_daily" else entry
        for entry in current
    ]

    plan = build_metadata_sync_plan(
        config=config,
        source_path=path,
        current_entries=latest,
        base_version=300,
        synced_at=datetime(2026, 8, 9, tzinfo=timezone.utc),
    )

    assert plan.activated_names == ("dq.fct_orders_daily",)
    assert plan.entries_to_insert[0].is_active is True
    assert plan.entries_to_insert[0].version == 300


def test_sync_rejects_cross_registry_ownership_conflict() -> None:
    """
    Ensure another source contract cannot silently take over an asset.

    Returns:
        None.
    """
    config, path, current = initial_plan()
    conflicting = replace(current[0], source_config_path="configs/metadata/other.yml")

    with pytest.raises(ValueError, match="ownership conflict"):
        build_metadata_sync_plan(
            config=config,
            source_path=path,
            current_entries=[conflicting, *current[1:]],
            base_version=200,
        )


# --- Defining Verification And DDL Tests
def test_exact_verification_passes_for_matching_latest_state() -> None:
    """
    Ensure matching source hashes and active states pass verification.

    Returns:
        None.
    """
    config, path, current = initial_plan()
    result = verify_metadata_registry(
        client=FakeClickHouseClient(list(current)),
        config=config,
        source_path=path,
    )

    assert result.status == "pass"
    assert result.expected_count == 3
    assert result.active_count == 3
    assert result.errors == ()


def test_exact_verification_reports_tombstoned_asset() -> None:
    """
    Ensure inactive latest state cannot be mistaken for trusted active metadata.

    Returns:
        None.
    """
    config, path, current = initial_plan()
    latest = [
        replace(entry, is_active=False) if entry.qualified_name == "dq.raw_orders" else entry
        for entry in current
    ]
    result = verify_metadata_registry(
        client=FakeClickHouseClient(latest),
        config=config,
        source_path=path,
    )

    assert result.status == "fail"
    assert "asset is tombstoned: dq.raw_orders" in result.errors


def test_exact_verification_reports_missing_physical_asset() -> None:
    """
    Ensure a YAML declaration cannot certify a ClickHouse asset that does not exist.

    Returns:
        None.
    """
    config, path, current = initial_plan()
    result = verify_metadata_registry(
        client=FakeClickHouseClient(
            list(current),
            missing_physical_assets={"dq.stg_orders"},
        ),
        config=config,
        source_path=path,
    )

    assert result.status == "fail"
    assert "physical ClickHouse asset missing: dq.stg_orders" in result.errors


def test_metadata_ddl_is_append_versioned_and_not_partitioned() -> None:
    """
    Ensure the small registry uses latest-state replacement without needless partitions.

    Returns:
        None.
    """
    ddl = Path("infra/init/clickhouse/05_metadata_tables.sql").read_text(encoding="utf-8")

    assert "CREATE TABLE IF NOT EXISTS dq.metadata_assets" in ddl
    assert "ENGINE = ReplacingMergeTree(version)" in ddl
    assert "ORDER BY qualified_name" in ddl
    assert "config_sha256          FixedString(64)" in ddl
    assert "PARTITION BY" not in ddl
    assert "DELETE" not in ddl.upper()
