####
## Smoke Readiness Tests for Agentic Data Quality Triage
## Author: Mario Caesar // hello@caesarmar.io // https://caesarmar.io/
####

# --- Importing Libraries
from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
from typing import Any

from scripts.smoke_readiness import (
    DEFAULT_CLICKHOUSE_TABLES,
    build_parser,
    build_table_count_query,
    build_table_exists_query,
    check_clickhouse_tables,
    check_control_plane_api,
    check_http_service,
    check_s3_buckets,
    render_text_summary,
    summarize_checks,
)


# --- Defining Test Fakes
@dataclass
class FakeQueryResult:
    """
    Minimal clickhouse-connect query result for readiness tests.

    Attributes:
        result_rows: Query result rows returned to the caller.
    """

    result_rows: list[tuple[Any, ...]]


class FakeClickHouseClient:
    """
    Fake ClickHouse client that returns table existence and row count values.

    Attributes:
        existing_tables: Mapping of fully qualified table names to row counts.
    """

    def __init__(self, existing_tables: dict[str, int]) -> None:
        """
        Initialize fake ClickHouse metadata.

        Args:
            existing_tables: Mapping of database.table names to row counts.

        Returns:
            None.
        """
        self.existing_tables = existing_tables

    def query(self, query: str) -> FakeQueryResult:
        """
        Return fake metadata/query results based on the incoming SQL string.

        Args:
            query: SQL query generated by smoke_readiness helpers.

        Returns:
            FakeQueryResult with one numeric cell.
        """
        if "FROM system.tables" in query:
            exists = any(table.split(".")[1] in query for table in self.existing_tables)

            return FakeQueryResult(result_rows=[(1 if exists else 0,)])

        for table_name, row_count in self.existing_tables.items():
            if f"FROM {table_name}" in query:
                return FakeQueryResult(result_rows=[(row_count,)])

        return FakeQueryResult(result_rows=[(0,)])


class FakeS3Client:
    """
    Fake boto3 S3 client for bucket readiness tests.

    Attributes:
        buckets: Bucket names returned by list_buckets.
    """

    def __init__(self, buckets: list[str]) -> None:
        """
        Initialize fake S3 bucket inventory.

        Args:
            buckets: Bucket names visible to the fake client.

        Returns:
            None.
        """
        self.buckets = buckets

    def list_buckets(self) -> dict[str, list[dict[str, str]]]:
        """
        Return fake S3 bucket list response.

        Returns:
            Dictionary matching the boto3 list_buckets response shape used by the script.
        """
        return {"Buckets": [{"Name": bucket} for bucket in self.buckets]}


# --- Defining Tests
def test_default_readiness_requires_metadata_registry_table() -> None:
    """
    Ensure platform readiness fails if the trusted metadata registry is absent.

    Returns:
        None.
    """
    assert "dq.metadata_assets" in DEFAULT_CLICKHOUSE_TABLES


def test_default_readiness_requires_schema_drift_evidence_tables() -> None:
    """
    Ensure readiness covers persisted schema snapshots and comparison results.

    Returns:
        None.
    """
    assert "dq.schema_snapshots" in DEFAULT_CLICKHOUSE_TABLES
    assert "dq.schema_drift_results" in DEFAULT_CLICKHOUSE_TABLES


def test_default_readiness_requires_agent_context_and_incident_memory_tables() -> None:
    """
    Ensure readiness covers temporary supervisor context and durable incident memory.

    Returns:
        None.
    """
    assert "dq.agent_run_context_events" in DEFAULT_CLICKHOUSE_TABLES
    assert "dq.incident_memory" in DEFAULT_CLICKHOUSE_TABLES


def test_build_table_exists_query_quotes_database_and_table() -> None:
    """
    Ensure table existence SQL targets ClickHouse system.tables safely.

    Returns:
        None.
    """
    query = build_table_exists_query(database="dq", table="alerts")

    assert "FROM system.tables" in query
    assert "database = 'dq'" in query
    assert "name = 'alerts'" in query


def test_build_table_count_query_uses_validated_qualified_table() -> None:
    """
    Ensure table count SQL preserves the expected fully qualified table name.

    Returns:
        None.
    """
    query = build_table_count_query("dq.raw_orders")

    assert query == "SELECT count() FROM dq.raw_orders"


def test_check_clickhouse_tables_reports_existing_and_missing_tables() -> None:
    """
    Ensure ClickHouse readiness checks return pass/fail table states.

    Returns:
        None.
    """
    client = FakeClickHouseClient(existing_tables={"dq.raw_orders": 42})

    checks = check_clickhouse_tables(client=client, table_names=["dq.raw_orders", "dq.alerts"])

    assert checks[0].status == "pass"
    assert checks[0].details["row_count"] == 42
    assert checks[1].status == "fail"
    assert checks[1].details["exists"] is False


def test_check_s3_buckets_reports_existing_and_missing_buckets() -> None:
    """
    Ensure S3 readiness checks return pass/fail bucket states.

    Returns:
        None.
    """
    client = FakeS3Client(buckets=["dq-landing"])

    checks = check_s3_buckets(client=client, bucket_names=["dq-landing", "dq-artifacts"])

    assert checks[0].status == "pass"
    assert checks[0].details["exists"] is True
    assert checks[1].status == "fail"
    assert checks[1].details["exists"] is False


def test_summarize_and_render_text_summary() -> None:
    """
    Ensure readiness summaries are compact and readable for CLI usage.

    Returns:
        None.
    """
    checks = check_s3_buckets(client=FakeS3Client(buckets=["dq-landing"]), bucket_names=["dq-landing"])
    summary = summarize_checks(checks)
    text = render_text_summary(summary)

    assert summary["status"] == "pass"
    assert summary["passed"] == 1
    assert "Agentic DQ smoke readiness" in text
    assert "[PASS] s3_bucket:dq-landing" in text


# --- Defining HTTP Service Tests
def test_check_http_service_reports_ready_status() -> None:
    """
    Ensure a successful CH-UI HTTP response becomes a passing readiness check.

    Returns:
        None.
    """
    class FakeResponse:
        """Context-managed HTTP response test double."""

        status = 200

        def __enter__(self) -> "FakeResponse":
            """Enter the fake response context."""
            return self

        def __exit__(self, *args: object) -> None:
            """Exit the fake response context."""

    def fake_opener(url: str, timeout: float) -> FakeResponse:
        """Return one healthy HTTP response."""
        assert url == "http://ch-ui:3488"
        assert timeout == 2.0

        return FakeResponse()

    check = check_http_service(
        service_name="ch-ui",
        url="http://ch-ui:3488",
        timeout_seconds=2.0,
        opener=fake_opener,
    )

    assert check.status == "pass"
    assert check.name == "http_service:ch-ui"
    assert check.details["status_code"] == 200


def test_check_http_service_reports_safe_failure_metadata() -> None:
    """
    Ensure HTTP failures expose type and endpoint without full exception text.

    Returns:
        None.
    """
    def failing_opener(url: str, timeout: float) -> None:
        """Raise a bounded timeout error."""
        raise TimeoutError("internal transport detail")

    check = check_http_service(
        service_name="ch-ui",
        url="http://ch-ui:3488",
        opener=failing_opener,
    )

    assert check.status == "fail"
    assert check.details == {
        "url": "http://ch-ui:3488",
        "error_type": "TimeoutError",
    }


def test_api_readiness_is_explicitly_opt_in() -> None:
    """
    Ensure the optional API profile is required only for API-dependent validation slices.

    Returns:
        None.
    """
    parser = build_parser()

    assert parser.parse_args([]).require_api is False
    assert parser.parse_args(["--require-api"]).require_api is True


def test_streamlit_readiness_is_required_by_default_and_can_be_skipped() -> None:
    """
    Ensure the operator UI is covered by default platform acceptance checks.

    Returns:
        None.
    """
    parser = build_parser()

    assert parser.parse_args([]).skip_streamlit is False
    assert parser.parse_args(["--skip-streamlit"]).skip_streamlit is True


def test_control_plane_readiness_checks_health_metadata_and_evidence_routes() -> None:
    """
    Ensure required API readiness covers health and representative read-only data routes.

    Returns:
        None.
    """
    requested_urls: list[str] = []

    class FakeResponse:
        """Context-managed successful HTTP response test double."""

        status = 200

        def __enter__(self) -> "FakeResponse":
            """Enter the fake response context."""
            return self

        def __exit__(self, *args: object) -> None:
            """Exit the fake response context."""

    def fake_opener(url: str, timeout: float) -> FakeResponse:
        """
        Capture each required API URL and return a healthy response.

        Args:
            url: Control-plane URL under test.
            timeout: Bounded request timeout.

        Returns:
            Successful fake response.
        """
        requested_urls.append(url)
        assert timeout == 3.0

        return FakeResponse()

    checks = check_control_plane_api(timeout_seconds=3.0, opener=fake_opener)

    assert [check.name for check in checks] == [
        "http_service:control-plane-api",
        "http_service:control-plane-daily-summary",
        "http_service:control-plane-life-history",
        "http_service:control-plane-incident-history",
        "http_service:control-plane-metadata-asset",
        "http_service:control-plane-dbt-blast-radius",
    ]
    assert all(check.status == "pass" for check in checks)
    assert requested_urls == [
        "http://api:8000/health",
        "http://api:8000/api/v1/summaries/daily?dt=2026-06-10",
        "http://api:8000/api/v1/evaluations/life?lookback_days=30&limit=1",
        "http://api:8000/api/v1/incidents/history?"
        "alert_reference=DQ-READINESS-000000&lookback_days=30&limit=1",
        "http://api:8000/api/v1/metadata/assets/dq.fct_orders_daily",
        "http://api:8000/api/v1/lineage/dbt/blast-radius?"
        "table_name=dq.raw_orders&"
        "manifest_s3_uri=s3%3A%2F%2Fdq-artifacts%2Fdbt-artifacts%2Forders%2Flatest%2Fmanifest.json&"
        "max_depth=5&max_nodes=100",
    ]


def test_compose_uses_valid_pinned_ch_ui_release_and_healthcheck() -> None:
    """
    Ensure local Compose cannot regress to an invalid or unprobed CH-UI image.

    Returns:
        None.
    """
    compose = Path("infra/docker-compose.yml").read_text(encoding="utf-8")
    example = Path(".env.example").read_text(encoding="utf-8")

    assert "ghcr.io/caioricciuti/ch-ui:v2.5.1" in compose
    assert "ghcr.io/caioricciuti/ch-ui:v2.5.1" in example
    assert "ghcr.io/caioricciuti/ch-ui:v1.6.4" not in compose
    assert 'test: ["CMD", "ch-ui", "server", "status"]' in compose


def test_compose_probes_streamlit_health_endpoint() -> None:
    """
    Ensure Docker and Airflow can distinguish a live Streamlit process from a ready UI.

    Returns:
        None.
    """
    compose = Path("infra/docker-compose.yml").read_text(encoding="utf-8")

    assert "http://localhost:8501/_stcore/health" in compose
