####
## Schema Drift Tests for Agentic Data Quality Triage
## Author: Mario Caesar // hello@caesarmar.io // https://caesarmar.io/
####

"""Validate schema contracts, deterministic comparison, persistence, and verification."""

# --- Importing Libraries
from __future__ import annotations

from datetime import datetime, timezone
from pathlib import Path
from typing import Any

import pytest
from pydantic import ValidationError

from pipelines.schema_drift.config import (
    SchemaContractConfig,
    load_named_schema_contract,
)
from pipelines.schema_drift.detector import (
    evaluate_schema_contract,
    schema_contract_sha256,
    validate_schema_run_id,
)
from pipelines.schema_drift.models import ObservedColumn
from pipelines.schema_drift.run_schema_drift import evaluate_gate_success
from pipelines.schema_drift.storage import (
    SCHEMA_DRIFT_RESULT_COLUMNS,
    SCHEMA_DRIFT_RESULTS_TABLE,
    SCHEMA_SNAPSHOT_COLUMNS,
    SCHEMA_SNAPSHOTS_TABLE,
    persist_schema_evaluation,
    read_schema_drift_ddl_statements,
    verify_persisted_schema_evaluation,
)


# --- Defining Test Fakes
class FakeQueryResult:
    """
    Minimal clickhouse-connect query result.

    Attributes:
        result_rows: Rows returned to schema drift functions.
    """

    def __init__(self, result_rows: list[tuple[Any, ...]]) -> None:
        """
        Initialize the fake query response.

        Args:
            result_rows: Query rows exposed by the fake.

        Returns:
            None.
        """
        self.result_rows = result_rows


class FakeSchemaClient:
    """
    Return configured system.columns rows for contracted tables.

    Attributes:
        schemas: Mapping of unqualified table names to system.columns rows.
    """

    def __init__(self, schemas: dict[str, list[tuple[Any, ...]]]) -> None:
        """
        Initialize schema metadata returned by query().

        Args:
            schemas: Table-name mapping of position/name/type/default rows.

        Returns:
            None.
        """
        self.schemas = schemas

    def query(self, query: str) -> FakeQueryResult:
        """
        Match a bounded system.columns query to configured rows.

        Args:
            query: SQL generated by fetch_observed_columns().

        Returns:
            FakeQueryResult for the selected table.
        """
        assert "FROM system.columns" in query
        assert "LIMIT 1000" in query

        for table_name, rows in self.schemas.items():
            if f"table = '{table_name}'" in query:
                return FakeQueryResult(rows)

        return FakeQueryResult([])


class FakeInsertClient:
    """
    Capture ClickHouse insert calls without external side effects.

    Attributes:
        inserts: Recorded table, rows, and columns for each insert.
    """

    def __init__(self) -> None:
        """Initialize an empty insert ledger."""
        self.inserts: list[dict[str, Any]] = []

    def insert(self, table: str, data: list[tuple[Any, ...]], column_names: tuple[str, ...]) -> None:
        """
        Record one insertion request.

        Args:
            table: Target ClickHouse table.
            data: Rows submitted for insertion.
            column_names: Explicit target column order.

        Returns:
            None.
        """
        self.inserts.append({"table": table, "data": data, "column_names": column_names})


class FakeVerificationClient:
    """
    Return persisted snapshot and comparison evidence for verification.

    Attributes:
        snapshot_rows: Latest snapshot rows for one run.
        comparison_rows: Latest comparison result rows for one run.
    """

    def __init__(
        self,
        snapshot_rows: list[tuple[Any, ...]],
        comparison_rows: list[tuple[Any, ...]],
    ) -> None:
        """
        Initialize persisted verification evidence.

        Args:
            snapshot_rows: qualified_name/hash/status/finding_count rows.
            comparison_rows: qualified_name/status/severity rows.

        Returns:
            None.
        """
        self.snapshot_rows   = snapshot_rows
        self.comparison_rows = comparison_rows

    def query(self, query: str) -> FakeQueryResult:
        """
        Return the evidence matching the requested persistence table.

        Args:
            query: Bounded verification SQL.

        Returns:
            FakeQueryResult containing snapshots or comparisons.
        """
        assert "FINAL" in query

        if f"FROM {SCHEMA_SNAPSHOTS_TABLE}" in query:
            return FakeQueryResult(self.snapshot_rows)
        if f"FROM {SCHEMA_DRIFT_RESULTS_TABLE}" in query:
            return FakeQueryResult(self.comparison_rows)

        raise AssertionError(f"Unexpected verification query: {query}")


# --- Defining Test Helpers
def load_orders_contract() -> SchemaContractConfig:
    """
    Load the repository orders schema contract.

    Returns:
        Validated schema contract.
    """
    contract, _ = load_named_schema_contract("orders")

    return contract


def clean_schema_rows(contract: SchemaContractConfig) -> dict[str, list[tuple[Any, ...]]]:
    """
    Build system.columns rows that exactly match a contract.

    Args:
        contract: Validated schema contract.

    Returns:
        Mapping of table names to ordered system.columns rows.
    """
    schemas: dict[str, list[tuple[Any, ...]]] = {}

    for table in contract.tables:
        table_name = table.qualified_name.split(".", maxsplit=1)[1]
        schemas[table_name] = [
            (
                position,
                column.name,
                column.data_type,
                column.default_kind,
                column.default_expression,
            )
            for position, column in enumerate(table.columns, start=1)
        ]

    return schemas


def evaluate_clean_contract() -> tuple[SchemaContractConfig, Any]:
    """
    Evaluate a contract against exact fake system metadata.

    Returns:
        Contract and clean SchemaDriftEvaluation.
    """
    contract = load_orders_contract()
    evaluation = evaluate_schema_contract(
        client=FakeSchemaClient(clean_schema_rows(contract)),
        contract=contract,
        run_id="manual__schema_drift_orders_test",
        observed_at=datetime(2026, 8, 7, tzinfo=timezone.utc),
    )

    return contract, evaluation


# --- Defining Contract Tests
def test_orders_schema_contract_is_complete_and_strict() -> None:
    """
    Ensure all current orders tables and columns have explicit expectations.

    Returns:
        None.
    """
    contract = load_orders_contract()
    tables   = {table.qualified_name: table for table in contract.tables}

    assert set(tables) == {"dq.raw_orders", "dq.stg_orders", "dq.fct_orders_daily"}
    assert sum(len(table.columns) for table in contract.tables) == 63
    assert contract.policy.missing_column == "critical"
    assert contract.policy.unexpected_columns == "warning"
    assert contract.policy.fail_on_severity == "critical"
    assert tables["dq.raw_orders"].columns[-1].default_expression == "generateUUIDv4()"


def test_schema_contract_rejects_duplicate_columns_and_unknown_fields() -> None:
    """
    Ensure config typos and duplicate column ownership fail closed.

    Returns:
        None.
    """
    contract = load_orders_contract()
    raw      = contract.model_dump(mode="json")
    raw["tables"][0]["columns"].append(dict(raw["tables"][0]["columns"][0]))

    with pytest.raises(ValidationError, match="Duplicate schema contract columns"):
        SchemaContractConfig.model_validate(raw)

    clean = contract.model_dump(mode="json")
    clean["unsupported_policy"] = True

    with pytest.raises(ValidationError, match="extra_forbidden"):
        SchemaContractConfig.model_validate(clean)


def test_schema_contract_hash_and_run_identity_are_stable() -> None:
    """
    Ensure contract evidence and run identifiers are deterministic and bounded.

    Returns:
        None.
    """
    contract = load_orders_contract()

    assert schema_contract_sha256(contract) == schema_contract_sha256(contract.model_copy(deep=True))
    assert len(schema_contract_sha256(contract)) == 64
    assert validate_schema_run_id("scheduled__2026-08-07T00:05:00+07:00")

    with pytest.raises(ValueError, match="unsupported characters"):
        validate_schema_run_id("manual__schema;drop table dq.raw_orders")


def test_observe_mode_keeps_findings_non_blocking_but_never_hides_operational_errors() -> None:
    """
    Ensure daily observability can continue after drift while strict errors still fail.

    Returns:
        None.
    """
    assert evaluate_gate_success(gate_mode="enforce", gate_crossed=True) is False
    assert evaluate_gate_success(gate_mode="observe", gate_crossed=True) is True
    assert evaluate_gate_success(
        gate_mode="observe",
        gate_crossed=True,
        blocking_errors=("missing persisted schema snapshot",),
    ) is False

    with pytest.raises(ValueError, match="Unsupported schema gate mode"):
        evaluate_gate_success(gate_mode="ignore", gate_crossed=True)


# --- Defining Comparison Tests
def test_clean_schema_evaluation_passes_with_stable_evidence() -> None:
    """
    Ensure an exact observed schema produces only passing comparisons.

    Returns:
        None.
    """
    _, evaluation = evaluate_clean_contract()

    assert evaluation.status == "pass"
    assert evaluation.should_fail is False
    assert evaluation.highest_severity == "info"
    assert len(evaluation.snapshots) == 3
    assert len(evaluation.results) == 258
    assert evaluation.findings == ()
    assert all(snapshot.status == "pass" for snapshot in evaluation.snapshots)


def test_schema_evaluation_retry_reuses_stable_storage_keys() -> None:
    """
    Ensure a task retry replaces prior evidence instead of creating new logical keys.

    Returns:
        None.
    """
    contract = load_orders_contract()
    schemas  = clean_schema_rows(contract)
    first = evaluate_schema_contract(
        client=FakeSchemaClient(schemas),
        contract=contract,
        run_id="manual__schema_drift_retry_test",
        observed_at=datetime(2026, 8, 7, 1, 0, tzinfo=timezone.utc),
    )
    retry = evaluate_schema_contract(
        client=FakeSchemaClient(schemas),
        contract=contract,
        run_id="manual__schema_drift_retry_test",
        observed_at=datetime(2026, 8, 7, 1, 5, tzinfo=timezone.utc),
    )

    assert [snapshot.snapshot_id for snapshot in first.snapshots] == [
        snapshot.snapshot_id for snapshot in retry.snapshots
    ]
    assert [result.result_id for result in first.results] == [result.result_id for result in retry.results]
    assert first.observed_at != retry.observed_at


def test_type_mismatch_is_critical_and_fails_the_gate() -> None:
    """
    Ensure incompatible type drift is classified as a critical gate failure.

    Returns:
        None.
    """
    contract = load_orders_contract()
    schemas  = clean_schema_rows(contract)
    row      = list(schemas["raw_orders"][1])
    row[2]   = "UInt64"
    schemas["raw_orders"][1] = tuple(row)

    evaluation = evaluate_schema_contract(
        client=FakeSchemaClient(schemas),
        contract=contract,
        run_id="manual__schema_drift_type_test",
    )
    findings = [result for result in evaluation.findings if result.check_type == "column_type"]

    assert evaluation.status == "fail"
    assert evaluation.should_fail is True
    assert len(findings) == 1
    assert findings[0].column_name == "order_id"
    assert findings[0].severity == "critical"
    assert findings[0].expected_value == "String"
    assert findings[0].actual_value == "UInt64"


def test_unexpected_column_is_a_warning_without_failing_critical_gate() -> None:
    """
    Ensure additive drift remains visible without failing the critical gate.

    Returns:
        None.
    """
    contract = load_orders_contract()
    schemas  = clean_schema_rows(contract)
    schemas["fct_orders_daily"].append((19, "experimental_metric", "UInt64", "", ""))

    evaluation = evaluate_schema_contract(
        client=FakeSchemaClient(schemas),
        contract=contract,
        run_id="manual__schema_drift_additive_test",
    )
    findings = [result for result in evaluation.findings if result.check_type == "unexpected_columns"]

    assert evaluation.status == "warn"
    assert evaluation.should_fail is False
    assert len(findings) == 1
    assert findings[0].severity == "warning"
    assert "experimental_metric" in findings[0].actual_value


def test_missing_table_and_column_are_explicit_critical_findings() -> None:
    """
    Ensure missing physical structures cannot be hidden by skipped comparisons.

    Returns:
        None.
    """
    contract = load_orders_contract()
    schemas  = clean_schema_rows(contract)
    schemas["raw_orders"] = schemas["raw_orders"][:-1]
    schemas.pop("stg_orders")

    evaluation = evaluate_schema_contract(
        client=FakeSchemaClient(schemas),
        contract=contract,
        run_id="manual__schema_drift_missing_test",
    )
    findings = {(result.qualified_name, result.check_type, result.column_name) for result in evaluation.findings}

    assert ("dq.raw_orders", "column_presence", "load_id") in findings
    assert ("dq.stg_orders", "table_presence", "") in findings
    assert evaluation.should_fail is True


def test_default_expression_drift_is_warning_evidence() -> None:
    """
    Ensure default changes are observable but do not cross the critical gate.

    Returns:
        None.
    """
    contract = load_orders_contract()
    schemas  = clean_schema_rows(contract)
    row      = list(schemas["raw_orders"][17])
    row[4]   = "1"
    schemas["raw_orders"][17] = tuple(row)

    evaluation = evaluate_schema_contract(
        client=FakeSchemaClient(schemas),
        contract=contract,
        run_id="manual__schema_drift_default_test",
    )
    findings = [result for result in evaluation.findings if result.check_type == "column_default"]

    assert evaluation.status == "warn"
    assert evaluation.should_fail is False
    assert len(findings) == 1
    assert findings[0].column_name == "is_test"


# --- Defining Persistence Tests
def test_schema_drift_ddl_is_versioned_and_append_preserving() -> None:
    """
    Ensure schema evidence tables retain history without destructive mutation.

    Returns:
        None.
    """
    ddl        = Path("infra/init/clickhouse/06_schema_drift_tables.sql").read_text(encoding="utf-8")
    statements = read_schema_drift_ddl_statements()

    assert len(statements) == 2
    assert "CREATE TABLE IF NOT EXISTS dq.schema_snapshots" in ddl
    assert "CREATE TABLE IF NOT EXISTS dq.schema_drift_results" in ddl
    assert ddl.count("ENGINE = ReplacingMergeTree(observed_at)") == 2
    assert "PARTITION BY toYYYYMM(observed_at)" in ddl
    assert "DELETE" not in ddl.upper()
    assert "TRUNCATE" not in ddl.upper()


def test_persist_schema_evaluation_uses_explicit_columns() -> None:
    """
    Ensure snapshot and comparison inserts preserve explicit storage contracts.

    Returns:
        None.
    """
    _, evaluation = evaluate_clean_contract()
    client        = FakeInsertClient()

    writes = persist_schema_evaluation(client=client, evaluation=evaluation)

    assert writes == {"snapshots_written": 3, "results_written": 258}
    assert [call["table"] for call in client.inserts] == [
        SCHEMA_SNAPSHOTS_TABLE,
        SCHEMA_DRIFT_RESULTS_TABLE,
    ]
    assert client.inserts[0]["column_names"] == SCHEMA_SNAPSHOT_COLUMNS
    assert client.inserts[1]["column_names"] == SCHEMA_DRIFT_RESULT_COLUMNS


def test_persisted_clean_evaluation_verifies_exact_contract_and_gate() -> None:
    """
    Ensure verification checks contract hashes, table coverage, and severity gate.

    Returns:
        None.
    """
    contract, evaluation = evaluate_clean_contract()
    padded_hash = (evaluation.contract_sha256 + "\x00\x00").encode("utf-8")
    snapshot_rows = [
        (snapshot.qualified_name, padded_hash, snapshot.status, snapshot.finding_count)
        for snapshot in evaluation.snapshots
    ]
    comparison_rows = [
        (result.qualified_name, result.status, result.severity)
        for result in evaluation.results
    ]
    client = FakeVerificationClient(snapshot_rows, comparison_rows)

    verification = verify_persisted_schema_evaluation(
        client=client,
        contract=contract,
        run_id=evaluation.run_id,
    )

    assert verification.status == "pass"
    assert verification.snapshot_count == 3
    assert verification.result_count == 258
    assert verification.finding_count == 0
    assert verification.gate_failure_count == 0
    assert verification.errors == ()
