####
## Metadata And Lineage Agent Tests for Agentic Data Quality Triage
## Author: Mario Caesar // hello@caesarmar.io // https://caesarmar.io/
####

"""Validate specialist contracts, policy, execution, audit, and Airflow trigger safety."""

# --- Importing Libraries
from __future__ import annotations

import json
from datetime import datetime, timezone
from typing import Any
from uuid import UUID, uuid4

import pytest
from pydantic import ValidationError

from agent.specialists.contracts import (
    AgentModelRoute,
    AgentResultEnvelope,
    AgentRiskTier,
    AgentTaskEnvelope,
    AgentTaskStatus,
    HandoffRecord,
    SupervisorState,
    build_supervisor_state,
)
from agent.specialists.metadata_lineage import (
    MetadataLineageRuntimeConfig,
    build_metadata_lineage_task,
    derive_metadata_lineage_parent_run_id,
    run_metadata_lineage_agent,
)
from agent.specialists.registry import (
    METADATA_LINEAGE_ALLOWED_TOOLS,
    METADATA_LINEAGE_SPECIALIST_NAME,
    enforce_task_capability,
    get_agent_capability,
    required_tools_for_task,
)
from pipelines.common.logging import logger
from scripts.trigger_airflow_metadata_lineage_agent import (
    METADATA_LINEAGE_DAG_ID,
    build_trigger_command,
    validate_trigger_inputs,
)
from scripts.run_metadata_lineage_agent import build_operator_summary
from scripts.verify_metadata_lineage_agent import verify_specialist_audit


# --- Defining Test Doubles
class FakeQueryResult:
    """Provide clickhouse-connect-compatible columns and result rows."""

    def __init__(self, columns: list[str], rows: list[tuple[Any, ...]]) -> None:
        """
        Initialize one fake query result.

        Args:
            columns: Query result column names.
            rows: Query result row tuples.

        Returns:
            None.
        """
        self.column_names = columns
        self.result_rows  = rows


class FakeAuditQueryClient:
    """Return predefined audit rows and retain the verifier SQL."""

    def __init__(self, rows: list[tuple[Any, ...]]) -> None:
        """
        Initialize the fake audit query client.

        Args:
            rows: Audit result rows returned by query calls.

        Returns:
            None.
        """
        self.rows = rows
        self.sql  = ""

    def query(self, sql: str) -> FakeQueryResult:
        """
        Record a query and return fixed audit rows.

        Args:
            sql: Read-only audit SQL generated by the verifier.

        Returns:
            FakeQueryResult with agent audit columns.
        """
        self.sql = sql

        return FakeQueryResult(
            columns=[
                "ts",
                "action",
                "tool_name",
                "status",
                "input_json",
                "output_json",
                "error_message",
                "duration_ms",
                "row_count",
            ],
            rows=self.rows,
        )


class AuditRecorder:
    """Capture specialist handoff audit writes without a live ClickHouse dependency."""

    def __init__(self) -> None:
        """Initialize an empty event list."""
        self.events: list[dict[str, Any]] = []

    def __call__(self, **kwargs: Any) -> UUID:
        """
        Record one audit write call.

        Args:
            kwargs: Keyword payload supplied to write_agent_audit_event.

        Returns:
            Correlated agent run UUID.
        """
        self.events.append(kwargs)

        return UUID(str(kwargs["agent_run_id"]))


# --- Defining Fixtures
def metadata_asset() -> dict[str, Any]:
    """
    Build one public candidate asset returned by the metadata catalog tool.

    Returns:
        Metadata asset dictionary for dq.raw_orders.
    """
    return {
        "qualified_name": "dq.raw_orders",
        "database_name": "dq",
        "table_name": "raw_orders",
        "display_name": "Raw Orders",
        "description": "Event-level orders loaded from SeaweedFS.",
        "dataset": "orders",
        "domain": "commerce",
        "data_layer": "raw",
        "technical_owner": "Data Platform Engineering",
        "business_owner": "Commerce Analytics",
        "grain": "One row per order event.",
        "refresh_frequency": "daily",
        "sla_time": "00:45",
        "sla_timezone": "Asia/Bangkok",
        "criticality": "high",
        "sensitivity": "internal",
        "contains_pii": False,
        "certification_status": "candidate",
        "lifecycle_status": "active",
        "tags": ["orders", "raw"],
        "synced_at": datetime(2026, 8, 8, tzinfo=timezone.utc),
    }


def lineage_payload() -> dict[str, Any]:
    """
    Build bounded direct lineage without raw or compiled SQL.

    Returns:
        Direct lineage summary dictionary.
    """
    return {
        "table_name": "dq.raw_orders",
        "matched": True,
        "node": {"unique_id": "source.dq.raw_orders", "resource_type": "source"},
        "parents": [],
        "children": [{"unique_id": "model.dq.stg_orders", "resource_type": "model"}],
        "tests": [],
        "summary": "Matched dq.raw_orders with one direct child.",
        "manifest_source": "warehouse/dbt/target/manifest.json",
    }


def blast_radius_payload() -> dict[str, Any]:
    """
    Build bounded downstream impact for the raw orders asset.

    Returns:
        Transitive blast-radius summary dictionary.
    """
    return {
        "table_name": "dq.raw_orders",
        "matched": True,
        "node": {"unique_id": "source.dq.raw_orders", "resource_type": "source"},
        "max_depth": 5,
        "max_nodes": 100,
        "max_depth_reached": 2,
        "truncated": False,
        "total_impacted_nodes": 3,
        "impacted_asset_count": 2,
        "impacted_test_count": 1,
        "unresolved_node_count": 0,
        "resource_type_counts": {"model": 2, "test": 1},
        "impacted_assets": [],
        "impacted_tests": [],
        "unresolved_nodes": [],
        "summary": "Found two downstream assets and one test.",
        "manifest_source": "warehouse/dbt/target/manifest.json",
    }


def successful_runtime(
    audit_recorder: AuditRecorder,
    call_log: list[str] | None = None,
) -> MetadataLineageRuntimeConfig:
    """
    Build deterministic specialist runtime dependencies for success-path tests.

    Args:
        audit_recorder: Handoff audit recorder.
        call_log: Optional ordered tool-call list.

    Returns:
        MetadataLineageRuntimeConfig using in-memory tool doubles.
    """
    calls = call_log if call_log is not None else []

    def fake_getter(**_: Any) -> dict[str, Any]:
        """Return one exact metadata asset."""
        calls.append("metadata_catalog")
        return metadata_asset()

    def fake_searcher(**_: Any) -> dict[str, Any]:
        """Return one bounded metadata search result."""
        calls.append("metadata_catalog")
        return {"assets": [metadata_asset()], "row_count": 1, "status": "success"}

    def fake_lineage(**_: Any) -> dict[str, Any]:
        """Return direct dbt lineage."""
        calls.append("dbt_lineage")
        return lineage_payload()

    def fake_blast_radius(**_: Any) -> dict[str, Any]:
        """Return bounded transitive dbt impact."""
        calls.append("dbt_blast_radius")
        return blast_radius_payload()

    return MetadataLineageRuntimeConfig(
        metadata_searcher=fake_searcher,
        metadata_getter=fake_getter,
        lineage_fetcher=fake_lineage,
        blast_radius_fetcher=fake_blast_radius,
        audit_client_factory=lambda **_: object(),
        audit_writer=audit_recorder,
    )


# --- Testing Handoff Contracts
def test_task_envelope_rejects_secret_bearing_context() -> None:
    """Secret-like keys must never enter shared specialist context."""
    with pytest.raises(ValidationError, match="forbidden context key"):
        AgentTaskEnvelope(
            parent_run_id=uuid4(),
            specialist_name=METADATA_LINEAGE_SPECIALIST_NAME,
            task_type="asset_context",
            allowed_tools=required_tools_for_task(
                METADATA_LINEAGE_SPECIALIST_NAME,
                "asset_context",
            ),
            input_payload={"qualified_name": "dq.raw_orders", "api_key": "not-allowed"},
        )


def test_supervisor_state_enforces_aggregate_token_budget() -> None:
    """Supervisor snapshots must reject specialist results above their token budget."""
    parent_run_id = uuid4()
    result        = AgentResultEnvelope(
        task_id=uuid4(),
        parent_run_id=parent_run_id,
        specialist_name="writer_agent",
        task_type="write_summary",
        status=AgentTaskStatus.SUCCESS,
        model_route=AgentModelRoute.QUICKTHINK_LLM,
        model_call_count=1,
        token_usage=200,
        estimated_cost_usd=0.001,
        duration_ms=100,
    )

    with pytest.raises(ValidationError, match="token budget exceeded"):
        SupervisorState(
            parent_run_id=parent_run_id,
            token_budget=100,
            specialist_results=[result],
        )


def test_build_supervisor_state_returns_bounded_defaults() -> None:
    """Initial supervisor state should be explicit, empty, and budget bounded."""
    parent_run_id = uuid4()
    state         = build_supervisor_state(parent_run_id=parent_run_id)

    assert state.parent_run_id == parent_run_id
    assert state.max_handoffs == 5
    assert state.active_task is None
    assert state.handoff_history == []
    assert state.specialist_results == []


def test_supervisor_state_rejects_handoff_count_above_budget() -> None:
    """Handoff history cannot silently grow beyond deterministic policy."""
    records = [
        HandoffRecord(
            task_id=uuid4(),
            specialist_name=METADATA_LINEAGE_SPECIALIST_NAME,
            task_type="asset_context",
            status=AgentTaskStatus.SUCCESS,
        ),
        HandoffRecord(
            task_id=uuid4(),
            specialist_name=METADATA_LINEAGE_SPECIALIST_NAME,
            task_type="blast_radius",
            status=AgentTaskStatus.SUCCESS,
        ),
    ]

    with pytest.raises(ValidationError, match="handoff budget exceeded"):
        SupervisorState(max_handoffs=1, handoff_history=records)


# --- Testing Capability Policy
def test_metadata_lineage_capability_is_read_only_and_deterministic() -> None:
    """The first specialist must expose only read-only tools and no-LLM routing."""
    capability = get_agent_capability(METADATA_LINEAGE_SPECIALIST_NAME)

    assert capability.allowed_tools == METADATA_LINEAGE_ALLOWED_TOOLS
    assert capability.mutation_allowed is False
    assert capability.approval_required is False
    assert capability.default_model_route == AgentModelRoute.NO_LLM_FALLBACK
    assert capability.maximum_risk_tier == AgentRiskTier.MEDIUM


def test_build_metadata_lineage_task_uses_exact_required_tools() -> None:
    """Task builders must not grant tools beyond the selected task's requirement."""
    task = build_metadata_lineage_task(
        parent_run_id=uuid4(),
        task_type="blast_radius",
        qualified_name="dq.raw_orders",
    )

    assert task.allowed_tools == required_tools_for_task(
        METADATA_LINEAGE_SPECIALIST_NAME,
        "blast_radius",
    )
    assert task.model_route == AgentModelRoute.NO_LLM_FALLBACK
    assert task.token_budget == 0
    assert task.context_references[0].reference == "dq.raw_orders"


def test_enforce_task_capability_rejects_unauthorized_tool() -> None:
    """A handoff cannot expand its tool permission beyond the capability registry."""
    valid_task = build_metadata_lineage_task(
        parent_run_id=uuid4(),
        task_type="blast_radius",
        qualified_name="dq.raw_orders",
    )
    unsafe_task = valid_task.model_copy(
        update={"allowed_tools": valid_task.allowed_tools + ("clickhouse_sql",)}
    )

    with pytest.raises(PermissionError, match="unauthorized specialist tools"):
        enforce_task_capability(unsafe_task)


# --- Testing Specialist Runtime
def test_metadata_lineage_agent_returns_typed_audited_asset_context() -> None:
    """Asset context should combine trusted metadata and bounded lineage evidence."""
    recorder = AuditRecorder()
    calls: list[str] = []
    task = build_metadata_lineage_task(
        parent_run_id=uuid4(),
        task_type="asset_context",
        qualified_name="dq.raw_orders",
        requester="airflow",
    )

    result = run_metadata_lineage_agent(
        task=task,
        config=successful_runtime(audit_recorder=recorder, call_log=calls),
    )

    assert result.status == AgentTaskStatus.SUCCESS
    assert result.model_route == AgentModelRoute.NO_LLM_FALLBACK
    assert result.token_usage == 0
    assert result.estimated_cost_usd == 0.0
    assert result.requires_human_approval is False
    assert result.structured_output["trust_status"] == "review"
    assert result.structured_output["blast_radius"]["impacted_asset_count"] == 2
    assert [item.evidence_type for item in result.evidence_references] == [
        "metadata_catalog_query",
        "metadata_asset",
        "dbt_lineage",
        "blast_radius",
    ]
    assert [item.source_tool for item in result.evidence_references] == [
        "metadata_catalog",
        "metadata_catalog",
        "dbt_lineage",
        "dbt_blast_radius",
    ]
    assert calls == ["metadata_catalog", "dbt_lineage", "dbt_blast_radius"]
    assert [event["action"] for event in recorder.events] == [
        "specialist_handoff_started",
        "specialist_handoff_completed",
    ]
    assert "compiled_sql" not in json.dumps(result.structured_output)
    assert "raw_sql" not in json.dumps(result.structured_output)

    operator_summary = build_operator_summary(result)

    assert "structured_output" not in operator_summary
    assert operator_summary["impacted_test_count"] == 1
    assert len(operator_summary["evidence_references"]) == 4


def test_trusted_asset_search_skips_lineage_tools() -> None:
    """Metadata search should not receive lineage permissions or execute lineage tools."""
    recorder = AuditRecorder()
    calls: list[str] = []
    task = build_metadata_lineage_task(
        parent_run_id=uuid4(),
        task_type="trusted_asset_search",
        query="orders",
    )

    result = run_metadata_lineage_agent(
        task=task,
        config=successful_runtime(audit_recorder=recorder, call_log=calls),
    )

    assert result.status == AgentTaskStatus.SUCCESS
    assert calls == ["metadata_catalog"]
    assert task.allowed_tools == ("metadata_catalog", "agent_audit_log")
    assert task.input_payload["qualified_name"] == ""
    assert task.context_references == []
    assert result.structured_output["lineage"] == {}
    assert result.structured_output["blast_radius"] == {}


def test_unauthorized_handoff_returns_blocked_without_tool_execution() -> None:
    """Policy rejection should remain isolated, audited, and side-effect free."""
    recorder = AuditRecorder()
    calls: list[str] = []
    valid_task = build_metadata_lineage_task(
        parent_run_id=uuid4(),
        task_type="blast_radius",
        qualified_name="dq.raw_orders",
    )
    unsafe_task = valid_task.model_copy(
        update={"allowed_tools": valid_task.allowed_tools + ("clickhouse_sql",)}
    )

    result = run_metadata_lineage_agent(
        task=unsafe_task,
        config=successful_runtime(audit_recorder=recorder, call_log=calls),
    )

    assert result.status == AgentTaskStatus.BLOCKED
    assert result.errors
    assert calls == []
    assert [event["action"] for event in recorder.events] == ["specialist_handoff_rejected"]
    assert recorder.events[0]["status"] == "blocked"


def test_specialist_tool_failure_returns_failed_without_domino_exception() -> None:
    """A failed metadata tool should return a failed envelope and retained handoff audit."""
    recorder = AuditRecorder()

    def failed_getter(**_: Any) -> dict[str, Any]:
        """Raise one deterministic metadata failure."""
        raise RuntimeError("metadata registry unavailable")

    runtime = successful_runtime(audit_recorder=recorder)
    runtime = MetadataLineageRuntimeConfig(
        metadata_searcher=runtime.metadata_searcher,
        metadata_getter=failed_getter,
        lineage_fetcher=runtime.lineage_fetcher,
        blast_radius_fetcher=runtime.blast_radius_fetcher,
        audit_client_factory=runtime.audit_client_factory,
        audit_writer=runtime.audit_writer,
    )
    task = build_metadata_lineage_task(
        parent_run_id=uuid4(),
        task_type="asset_context",
        qualified_name="dq.raw_orders",
    )

    result = run_metadata_lineage_agent(task=task, config=runtime)

    assert result.status == AgentTaskStatus.FAILED
    assert "metadata registry unavailable" in result.errors[0]
    assert [event["action"] for event in recorder.events] == [
        "specialist_handoff_started",
        "specialist_handoff_failed",
    ]


# --- Testing Airflow Trigger Safety
def test_trigger_input_validation_rejects_shell_sensitive_search() -> None:
    """Airflow trigger configuration must reject shell-sensitive search text."""
    with pytest.raises(ValueError, match="unsupported characters"):
        validate_trigger_inputs(
            task_type="trusted_asset_search",
            qualified_name="",
            query="orders'; rm -rf /",
            max_depth=5,
            max_nodes=100,
        )


def test_trigger_command_uses_bounded_json_configuration() -> None:
    """Trigger helper should pass structured JSON instead of interpolated shell commands."""
    command = build_trigger_command(
        task_type="asset_context",
        qualified_name="dq.raw_orders",
        query="orders",
        max_depth=5,
        max_nodes=100,
        run_id="manual__metadata_lineage_test",
    )
    conf = json.loads(command[command.index("-c") + 1])

    assert command[0:3] == ["airflow", "dags", "trigger"]
    assert command[-1] == METADATA_LINEAGE_DAG_ID
    assert conf == {
        "task_type": "asset_context",
        "qualified_name": "dq.raw_orders",
        "query": "orders",
        "max_depth": 5,
        "max_nodes": 100,
    }


def test_trusted_search_trigger_strips_unneeded_asset_context() -> None:
    """Search triggers must not forward an unrelated exact asset to the specialist."""
    command = build_trigger_command(
        task_type="trusted_asset_search",
        qualified_name="dq.raw_orders",
        query="orders",
        max_depth=5,
        max_nodes=100,
        run_id="manual__metadata_lineage_search_test",
    )
    conf = json.loads(command[command.index("-c") + 1])

    assert conf["qualified_name"] == ""


# --- Testing Audit Verification
def test_verify_specialist_audit_requires_complete_zero_cost_handoff(monkeypatch) -> None:
    """Verifier should accept only complete, read-only, zero-cost specialist evidence."""
    run_id       = "manual__metadata_lineage_verified"
    parent_run_id = derive_metadata_lineage_parent_run_id(run_id)
    completion   = {
        "result_status": "success",
        "confidence": 0.85,
        "evidence_reference_count": 3,
        "qualified_names": ["dq.raw_orders"],
        "trust_status": "review",
        "impacted_asset_count": 2,
        "impacted_test_count": 1,
        "model_route": "no_llm_fallback",
        "token_usage": 0,
        "estimated_cost_usd": 0.0,
        "requires_human_approval": False,
    }
    rows = [
        (datetime.now(timezone.utc), "specialist_handoff_started", "metadata_lineage_agent", "running", "{}", "{}", "", None, None),
        (datetime.now(timezone.utc), "get_metadata_asset", "metadata_catalog", "success", "{}", "{}", "", 1, 1),
        (datetime.now(timezone.utc), "fetch_dbt_lineage", "dbt_lineage", "success", "{}", "{}", "", 1, 1),
        (datetime.now(timezone.utc), "fetch_dbt_blast_radius", "dbt_blast_radius", "success", "{}", "{}", "", 1, 3),
        (datetime.now(timezone.utc), "specialist_handoff_completed", "metadata_lineage_agent", "success", "{}", json.dumps(completion), "", 10, None),
    ]
    client = FakeAuditQueryClient(rows=rows)

    monkeypatch.setattr(
        "scripts.verify_metadata_lineage_agent.build_clickhouse_client",
        lambda **_: client,
    )

    summary = verify_specialist_audit(
        run_id=run_id,
        task_type="asset_context",
        qualified_name="dq.raw_orders",
    )

    assert summary["parent_run_id"] == str(parent_run_id)
    assert summary["result_status"] == "success"
    assert summary["model_route"] == "no_llm_fallback"
    assert summary["audit_event_count"] == 5
    assert "LIMIT 100" in client.sql
    assert str(parent_run_id) in client.sql


logger.info("Loaded Metadata and Lineage Agent contract tests")
