####
## Alert Lifecycle Tool for Agentic Data Quality Triage
## Author: Mario Caesar // hello@caesarmar.io // https://caesarmar.io/
####

# --- Importing Libraries
from __future__ import annotations

import argparse
import json
import sys
import time
from pathlib import Path
from typing import Any
from uuid import UUID, uuid4


# --- Configuring Project Path
PROJECT_ROOT = Path(__file__).resolve().parents[2]

# Add repo root before importing project packages when this file is executed by path.
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

from agent.state import Alert
from agent.tools.alerts import load_alert
from agent.tools.audit_log import write_agent_audit_event
from pipelines.common.clickhouse import build_clickhouse_client, quote_sql_literal
from pipelines.common.logging import logger


# --- Defining Constants
TOOL_NAME    = "alert_lifecycle"
ALERTS_TABLE = "dq.alerts"


# --- Defining Functions
def build_mark_alert_triaged_sql(alert_key: str, report_s3_uri: str) -> str:
    """
    Build the ClickHouse mutation used to mark an alert as triaged.

    Args:
        alert_key: Stable alert key from dq.alerts.
        report_s3_uri: Markdown report S3 URI generated by the triage workflow.

    Returns:
        ClickHouse ALTER UPDATE statement.
    """
    # Do not update updated_at here; ClickHouse blocks mutations on ReplacingMergeTree version columns.
    return f"""
        ALTER TABLE {ALERTS_TABLE}
        UPDATE
            status = 'triaged',
            report_s3_uri = {quote_sql_literal(report_s3_uri)}
        WHERE alert_key = {quote_sql_literal(alert_key)}
          AND status = 'open'
        SETTINGS mutations_sync = 1
    """


def build_alert_lifecycle_summary_sql(alert_key: str) -> str:
    """
    Build a small verification query for the updated alert lifecycle row.

    Args:
        alert_key: Stable alert key from dq.alerts.

    Returns:
        ClickHouse SELECT statement returning lifecycle fields.
    """
    return f"""
        SELECT
            alert_key,
            status,
            report_s3_uri,
            updated_at
        FROM {ALERTS_TABLE}
        WHERE alert_key = {quote_sql_literal(alert_key)}
        ORDER BY updated_at DESC
        LIMIT 1
    """


def query_lifecycle_row(client: Any, alert_key: str) -> dict[str, Any]:
    """
    Read the latest lifecycle fields for one alert key.

    Args:
        client: clickhouse-connect client instance.
        alert_key: Stable alert key from dq.alerts.

    Returns:
        Dictionary with lifecycle fields, or an empty dictionary when no row exists.
    """
    sql    = build_alert_lifecycle_summary_sql(alert_key=alert_key)
    result = client.query(sql)
    rows   = result.result_rows

    if not rows:
        logger.warning("Alert lifecycle row not found after update | alert_key=%s", alert_key)

        return {}

    columns = list(result.column_names or [])
    row     = dict(zip(columns, rows[0], strict=False))

    logger.info(
        "Read alert lifecycle row | alert_key=%s status=%s report_s3_uri=%s",
        alert_key,
        row.get("status"),
        row.get("report_s3_uri"),
    )

    return row


def mark_alert_triaged(
    alert: Alert,
    report_s3_uri: str,
    agent_run_id: UUID | str | None = None,
    clickhouse_host: str | None = None,
    clickhouse_port: int | None = None,
) -> dict[str, Any]:
    """
    Mark an open alert as triaged after report artifacts are stored.

    Args:
        alert: Alert model being investigated.
        report_s3_uri: Markdown report S3 URI generated by the triage workflow.
        agent_run_id: Optional agent run UUID used for audit correlation.
        clickhouse_host: Optional ClickHouse host override.
        clickhouse_port: Optional ClickHouse HTTP port override.

    Returns:
        Result dictionary. Failures are returned as status=failed instead of raised.
    """
    client                = build_clickhouse_client(host=clickhouse_host, port=clickhouse_port)
    resolved_agent_run_id = UUID(str(agent_run_id)) if agent_run_id else uuid4()
    started_monotonic     = time.monotonic()
    sql                   = build_mark_alert_triaged_sql(alert_key=alert.alert_key, report_s3_uri=report_s3_uri)

    logger.info(
        "Marking alert as triaged | agent_run_id=%s alert_key=%s report_s3_uri=%s",
        resolved_agent_run_id,
        alert.alert_key,
        report_s3_uri,
    )

    try:
        # This is the only sanctioned alert lifecycle mutation; evidence SQL remains read-only.
        client.command(sql)

        lifecycle_row = query_lifecycle_row(client=client, alert_key=alert.alert_key)
        duration_ms   = int((time.monotonic() - started_monotonic) * 1000)
        result        = {
            "status": "success",
            "alert_key": alert.alert_key,
            "alert_status": lifecycle_row.get("status", "triaged"),
            "report_s3_uri": lifecycle_row.get("report_s3_uri", report_s3_uri),
        }

        write_agent_audit_event(
            client=client,
            action="mark_alert_triaged",
            status="success",
            agent_run_id=resolved_agent_run_id,
            alert_id=alert.alert_id,
            alert_key=alert.alert_key,
            tool_name=TOOL_NAME,
            duration_ms=duration_ms,
            input_payload={"report_s3_uri": report_s3_uri},
            output_payload=result,
            sql=sql,
            row_count=1,
            report_s3_uri=report_s3_uri,
        )

        logger.info("Alert marked as triaged | agent_run_id=%s alert_key=%s", resolved_agent_run_id, alert.alert_key)

        return result

    except Exception as exc:
        duration_ms = int((time.monotonic() - started_monotonic) * 1000)
        result      = {
            "status": "failed",
            "alert_key": alert.alert_key,
            "report_s3_uri": report_s3_uri,
            "error_type": type(exc).__name__,
            "error_message": str(exc),
        }

        logger.exception("Failed to mark alert as triaged | alert_key=%s", alert.alert_key)

        try:
            write_agent_audit_event(
                client=client,
                action="mark_alert_triaged",
                status="failed",
                agent_run_id=resolved_agent_run_id,
                alert_id=alert.alert_id,
                alert_key=alert.alert_key,
                tool_name=TOOL_NAME,
                duration_ms=duration_ms,
                input_payload={"report_s3_uri": report_s3_uri},
                output_payload={"error_type": type(exc).__name__},
                error_message=str(exc),
                sql=sql,
                report_s3_uri=report_s3_uri,
            )

        except Exception:
            logger.exception("Failed to write alert lifecycle audit event | alert_key=%s", alert.alert_key)

        return result


def build_parser() -> argparse.ArgumentParser:
    """
    Build the command-line parser for manual alert lifecycle updates.

    Returns:
        Configured ArgumentParser instance.
    """
    parser = argparse.ArgumentParser(description="Mark one dq.alerts row as triaged after report storage.")

    parser.add_argument("--alert-id", default=None, help="Optional ClickHouse alert UUID.")
    parser.add_argument("--alert-key", default=None, help="Optional stable alert key.")
    parser.add_argument("--report-s3-uri", required=True, help="Markdown report S3 URI.")
    parser.add_argument("--clickhouse-host", default=None, help="Optional ClickHouse host override.")
    parser.add_argument("--clickhouse-port", type=int, default=None, help="Optional ClickHouse HTTP port override.")

    return parser


def main() -> None:
    """
    Parse CLI arguments and mark one alert as triaged.

    Returns:
        None.

    Raises:
        ValueError: If neither alert_id nor alert_key is provided.
    """
    parser = build_parser()
    args   = parser.parse_args()

    if not args.alert_id and not args.alert_key:
        raise ValueError("Provide --alert-id or --alert-key.")

    alert = load_alert(
        alert_id=args.alert_id,
        alert_key=args.alert_key,
        clickhouse_host=args.clickhouse_host,
        clickhouse_port=args.clickhouse_port,
    )
    result = mark_alert_triaged(
        alert=alert,
        report_s3_uri=args.report_s3_uri,
        clickhouse_host=args.clickhouse_host,
        clickhouse_port=args.clickhouse_port,
    )

    print(json.dumps(result, indent=2, default=str))


# --- Running CLI Entrypoint
if __name__ == "__main__":
    main()
