####
## Alert Lifecycle Tool for Agentic Data Quality Triage
## Author: Mario Caesar // hello@caesarmar.io // https://caesarmar.io/
####

# --- Importing Libraries
from __future__ import annotations

import argparse
import json
import sys
import time
from datetime import datetime, timedelta, timezone
from pathlib import Path
from typing import Any
from uuid import UUID, uuid4


# --- Configuring Project Path
PROJECT_ROOT = Path(__file__).resolve().parents[2]

# Add repo root before importing project packages when this file is executed by path.
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

from agent.state import Alert
from agent.tools.alerts import load_alert
from agent.tools.audit_log import build_audit_idempotency_key, write_agent_audit_event
from pipelines.common.clickhouse import build_clickhouse_client, quote_sql_literal
from pipelines.common.logging import logger


# --- Defining Constants
TOOL_NAME    = "alert_lifecycle"
ALERTS_TABLE = "dq.alerts"

ALERT_VERSION_COLUMNS = (
    "alert_id",
    "alert_key",
    "alert_display_id",
    "created_at",
    "updated_at",
    "status",
    "alert_type",
    "severity",
    "table_name",
    "metric",
    "dt",
    "dimension",
    "observed_value",
    "expected_value",
    "threshold_value",
    "source_check_run_id",
    "details_json",
    "report_s3_uri",
    "acknowledged_by",
    "resolved_at",
)


# --- Defining Functions
def build_alert_lifecycle_source_sql(alert_key: str) -> str:
    """
    Build the bounded read used to copy the current alert lifecycle version.

    Args:
        alert_key: Stable alert key from dq.alerts.

    Returns:
        ClickHouse SELECT statement returning one current alert version.
    """
    selected_columns = ",\n            ".join(ALERT_VERSION_COLUMNS)

    return f"""
        SELECT
            {selected_columns}
        FROM {ALERTS_TABLE} FINAL
        WHERE alert_key = {quote_sql_literal(alert_key)}
        ORDER BY updated_at DESC
        LIMIT 1
    """


def normalize_version_timestamp(value: Any) -> datetime:
    """
    Normalize a ClickHouse lifecycle timestamp into a timezone-aware datetime.

    Args:
        value: DateTime-like value returned by clickhouse-connect.

    Returns:
        UTC-aware datetime suitable for monotonic version comparison.

    Raises:
        TypeError: If ClickHouse returned an unsupported timestamp type.
    """
    if not isinstance(value, datetime):
        raise TypeError(f"Alert lifecycle updated_at must be datetime, received {type(value).__name__}.")

    if value.tzinfo is None:
        return value.replace(tzinfo=timezone.utc)

    return value.astimezone(timezone.utc)


def build_alert_lifecycle_version_row(
    source_row: dict[str, Any],
    report_s3_uri: str,
    observed_at: datetime | None = None,
) -> list[Any]:
    """
    Copy one alert row and replace only its lifecycle version fields.

    Args:
        source_row: Current alert version keyed by ALERT_VERSION_COLUMNS.
        report_s3_uri: Markdown report S3 URI generated by triage.
        observed_at: Optional UTC timestamp override used by deterministic tests.

    Returns:
        Row-oriented values matching ALERT_VERSION_COLUMNS.

    Raises:
        ValueError: If a required source column is missing.
        TypeError: If source updated_at is not a datetime.
    """
    missing_columns = [column for column in ALERT_VERSION_COLUMNS if column not in source_row]

    if missing_columns:
        raise ValueError(f"Alert lifecycle source row is missing columns: {', '.join(missing_columns)}")

    current_version = normalize_version_timestamp(source_row["updated_at"])
    requested_time  = normalize_version_timestamp(observed_at or datetime.now(timezone.utc))
    next_version    = max(requested_time, current_version + timedelta(milliseconds=1))
    version_row     = dict(source_row)

    # ReplacingMergeTree chooses the row with the largest updated_at version.
    version_row["updated_at"]    = next_version
    version_row["status"]        = "triaged"
    version_row["report_s3_uri"] = report_s3_uri

    return [version_row[column] for column in ALERT_VERSION_COLUMNS]


def query_alert_lifecycle_source_row(client: Any, alert_key: str) -> dict[str, Any]:
    """
    Read the complete current alert version used by the lifecycle append.

    Args:
        client: clickhouse-connect client instance.
        alert_key: Stable alert key from dq.alerts.

    Returns:
        Complete alert version dictionary, or an empty dictionary when absent.
    """
    sql    = build_alert_lifecycle_source_sql(alert_key=alert_key)
    result = client.query(sql)
    rows   = result.result_rows

    if not rows:
        logger.warning("Alert lifecycle source row not found | alert_key=%s", alert_key)

        return {}

    columns = list(result.column_names or [])

    return dict(zip(columns, rows[0], strict=False))


def build_alert_lifecycle_summary_sql(alert_key: str) -> str:
    """
    Build a small verification query for the updated alert lifecycle row.

    Args:
        alert_key: Stable alert key from dq.alerts.

    Returns:
        ClickHouse SELECT statement returning lifecycle fields.
    """
    return f"""
        SELECT
            alert_key,
            status,
            report_s3_uri,
            updated_at
        FROM {ALERTS_TABLE} FINAL
        WHERE alert_key = {quote_sql_literal(alert_key)}
        ORDER BY updated_at DESC
        LIMIT 1
    """


def query_lifecycle_row(client: Any, alert_key: str) -> dict[str, Any]:
    """
    Read the latest lifecycle fields for one alert key.

    Args:
        client: clickhouse-connect client instance.
        alert_key: Stable alert key from dq.alerts.

    Returns:
        Dictionary with lifecycle fields, or an empty dictionary when no row exists.
    """
    sql    = build_alert_lifecycle_summary_sql(alert_key=alert_key)
    result = client.query(sql)
    rows   = result.result_rows

    if not rows:
        logger.warning("Alert lifecycle row not found after update | alert_key=%s", alert_key)

        return {}

    columns = list(result.column_names or [])
    row     = dict(zip(columns, rows[0], strict=False))

    logger.info(
        "Read alert lifecycle row | alert_key=%s status=%s report_s3_uri=%s",
        alert_key,
        row.get("status"),
        row.get("report_s3_uri"),
    )

    return row


def mark_alert_triaged(
    alert: Alert,
    report_s3_uri: str,
    agent_run_id: UUID | str | None = None,
    clickhouse_host: str | None = None,
    clickhouse_port: int | None = None,
) -> dict[str, Any]:
    """
    Append or reuse a triaged alert version after report artifacts are stored.

    Args:
        alert: Alert model being investigated.
        report_s3_uri: Markdown report S3 URI generated by the triage workflow.
        agent_run_id: Optional agent run UUID used for audit correlation.
        clickhouse_host: Optional ClickHouse host override.
        clickhouse_port: Optional ClickHouse HTTP port override.

    Returns:
        Result dictionary. Failures are returned as status=failed instead of raised.
    """
    client                = build_clickhouse_client(host=clickhouse_host, port=clickhouse_port)
    resolved_agent_run_id = UUID(str(agent_run_id)) if agent_run_id else uuid4()
    started_monotonic     = time.monotonic()
    source_sql            = build_alert_lifecycle_source_sql(alert_key=alert.alert_key)

    logger.info(
        "Marking alert as triaged | agent_run_id=%s alert_key=%s report_s3_uri=%s",
        resolved_agent_run_id,
        alert.alert_key,
        report_s3_uri,
    )

    try:
        source_row = query_alert_lifecycle_source_row(client=client, alert_key=alert.alert_key)

        if not source_row:
            raise RuntimeError("Alert lifecycle source row was not found.")

        version_written = not (
            source_row.get("status") == "triaged"
            and source_row.get("report_s3_uri") == report_s3_uri
        )

        if version_written:
            version_row = build_alert_lifecycle_version_row(
                source_row=source_row,
                report_s3_uri=report_s3_uri,
            )

            # This is the only sanctioned lifecycle write; evidence SQL remains read-only.
            client.insert(
                table=ALERTS_TABLE,
                data=[version_row],
                column_names=ALERT_VERSION_COLUMNS,
            )

            logger.info(
                "Appended alert lifecycle version | alert_key=%s updated_at=%s",
                alert.alert_key,
                version_row[ALERT_VERSION_COLUMNS.index("updated_at")],
            )

        else:
            logger.info(
                "Alert lifecycle already references report; version append skipped | alert_key=%s",
                alert.alert_key,
            )

        lifecycle_row = query_lifecycle_row(client=client, alert_key=alert.alert_key)

        if lifecycle_row.get("status") != "triaged":
            raise RuntimeError("Alert lifecycle readback did not retain triaged status.")

        if lifecycle_row.get("report_s3_uri") != report_s3_uri:
            raise RuntimeError("Alert lifecycle readback did not retain the latest report URI.")

        duration_ms   = int((time.monotonic() - started_monotonic) * 1000)
        result        = {
            "status": "success",
            "alert_key": alert.alert_key,
            "alert_status": lifecycle_row.get("status", "triaged"),
            "report_s3_uri": lifecycle_row.get("report_s3_uri", report_s3_uri),
            "version_written": version_written,
        }
        audit_idempotency_key = build_audit_idempotency_key(
            "mark_alert_triaged",
            resolved_agent_run_id,
            alert.alert_key,
            report_s3_uri,
        )

        write_agent_audit_event(
            client=client,
            action="mark_alert_triaged",
            status="success",
            agent_run_id=resolved_agent_run_id,
            alert_id=alert.alert_id,
            alert_key=alert.alert_key,
            tool_name=TOOL_NAME,
            duration_ms=duration_ms,
            input_payload={
                "report_s3_uri": report_s3_uri,
                "write_mode": "append_replacing_version",
            },
            output_payload=result,
            sql=source_sql,
            row_count=int(version_written),
            report_s3_uri=report_s3_uri,
            idempotency_key=audit_idempotency_key,
        )

        logger.info("Alert marked as triaged | agent_run_id=%s alert_key=%s", resolved_agent_run_id, alert.alert_key)

        return result

    except Exception as exc:
        duration_ms = int((time.monotonic() - started_monotonic) * 1000)
        result      = {
            "status": "failed",
            "alert_key": alert.alert_key,
            "report_s3_uri": report_s3_uri,
            "error_type": type(exc).__name__,
            "error_message": str(exc),
        }

        logger.exception("Failed to mark alert as triaged | alert_key=%s", alert.alert_key)

        try:
            write_agent_audit_event(
                client=client,
                action="mark_alert_triaged",
                status="failed",
                agent_run_id=resolved_agent_run_id,
                alert_id=alert.alert_id,
                alert_key=alert.alert_key,
                tool_name=TOOL_NAME,
                duration_ms=duration_ms,
                input_payload={"report_s3_uri": report_s3_uri},
                output_payload={"error_type": type(exc).__name__},
                error_message=str(exc),
                sql=source_sql,
                report_s3_uri=report_s3_uri,
            )

        except Exception:
            logger.exception("Failed to write alert lifecycle audit event | alert_key=%s", alert.alert_key)

        return result


def build_parser() -> argparse.ArgumentParser:
    """
    Build the command-line parser for manual alert lifecycle updates.

    Returns:
        Configured ArgumentParser instance.
    """
    parser = argparse.ArgumentParser(description="Mark one dq.alerts row as triaged after report storage.")

    parser.add_argument("--alert-id", default=None, help="Optional ClickHouse alert UUID.")
    parser.add_argument("--alert-key", default=None, help="Optional stable alert key.")
    parser.add_argument("--report-s3-uri", required=True, help="Markdown report S3 URI.")
    parser.add_argument("--clickhouse-host", default=None, help="Optional ClickHouse host override.")
    parser.add_argument("--clickhouse-port", type=int, default=None, help="Optional ClickHouse HTTP port override.")

    return parser


def main() -> None:
    """
    Parse CLI arguments and mark one alert as triaged.

    Returns:
        None.

    Raises:
        ValueError: If neither alert_id nor alert_key is provided.
    """
    parser = build_parser()
    args   = parser.parse_args()

    if not args.alert_id and not args.alert_key:
        raise ValueError("Provide --alert-id or --alert-key.")

    alert = load_alert(
        alert_id=args.alert_id,
        alert_key=args.alert_key,
        clickhouse_host=args.clickhouse_host,
        clickhouse_port=args.clickhouse_port,
    )
    result = mark_alert_triaged(
        alert=alert,
        report_s3_uri=args.report_s3_uri,
        clickhouse_host=args.clickhouse_host,
        clickhouse_port=args.clickhouse_port,
    )

    print(json.dumps(result, indent=2, default=str))


# --- Running CLI Entrypoint
if __name__ == "__main__":
    main()
